-- Revenue by store: Write a query to calculate the total revenue generated by each store.
select  st.store_name,sum(p.product_id*w.quantity*p.list_price) as revenue
from stores st
join stocks w using(store_id)
join products p using(product_id)
group by st.store_name